export const ACTIVITY_HINTS = {
  INDOOR_DAY: 'Indoor day',
  DO_NOT_BIKE: 'Do not bike',
  SLIPPERY_OUTSIDE: 'Slippery outside',
  COZY_INSIDE: 'Cozy inside',
  UMBRELLA_ERRANDS: 'Umbrella errands',
  RAINY_DAY: 'Rainy day',
  DENSE_FOG: 'Dense fog',
  FOG_LIKELY: 'Fog likely',
  MISTY_WALK: 'Misty walk',
  HEAVY_AIR: 'Heavy air',
  HAZY_OUTDOORS: 'Hazy outdoors',
  COLD_STORM: 'Cold storm',
  STORMY_DAY: 'Stormy day',
  BITING_WIND: 'Biting wind',
  CUTTING_WIND: 'Cutting wind',
  BRISK_AIR: 'Brisk air',
  WINDY_BUT_PLEASANT: 'Windy but pleasant',
  COOLING_BREEZE: 'Cooling breeze',
  WINDY_DAY: 'Windy day',
  AIR_FEELS_THICK: 'Air feels thick',
  STICKY_HEAT: 'Sticky heat',
  DRY_HEAT: 'Dry heat',
  HOT_AND_SWEATY: 'Hot and sweaty',
  BEACH_WEATHER: 'Beach weather',
  HUMID_EVENING: 'Humid evening',
  TERRACE_READY: 'Terrace ready',
  TERRACE_WEATHER: 'Terrace weather',
  DINNER_OUTSIDE: 'Dinner outside',
  CLEAR_WINTER_DAY: 'Clear winter day',
  FREEZING_WALK: 'Freezing walk',
  CRISP_BLUE_SKIES: 'Crisp blue skies',
  COLD_AND_CRISP: 'Cold and crisp',
  SUNNY_LIGHT_COAT: 'Sunny, light coat',
  DRIZZLE_AND_JACKET: 'Drizzle + jacket',
  LAYER_UP: 'Layer up',
  LONG_WALK_DAY: 'Long walk day',
  FRESH_AIR_WALK: 'Fresh-air walk',
  ERRAND_WEATHER: 'Errand weather',
  GREAT_FOR_CYCLING: 'Great for cycling',
  RAIN_BREAKS: 'Rain breaks',
  NICE_OUTDOORS: 'Nice outdoors',
  GOLDEN_DAY: 'Golden day',
  PICNIC_WEATHER: 'Picnic weather',
  BIKE_FRIENDLY: 'Bike-friendly',
  BETWEEN_SHOWERS: 'Between showers',
  EASY_OUTDOOR_DAY: 'Easy outdoor day',
  TERRACE_GAMBLE: 'Terrace gamble',
  BRING_A_LIGHT_SHELL: 'Bring a light shell',
  CRYSTAL_CLEAR_DAY: 'Crystal-clear day',
  BIG_SKY_DAY: 'Big-sky day',
  CLEAR_SKIES: 'Clear skies',
  GOOD_OUTDOORS: 'Good outdoors',
  OTHER_DAY_WET: 'other day wet',
  OTHER_DAY_STORMY: 'other day stormy',
  OTHER_DAY_RAINY: 'other day rainy',
  OTHER_DAY_COLD: 'other day cold',
  OTHER_DAY_MEH: 'other day meh',
} as const;

export type ActivityHint = (typeof ACTIVITY_HINTS)[keyof typeof ACTIVITY_HINTS];
